# Generated by Django 5.1.2 on 2024-10-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("draft", "Draft"),
                ],
                default="draft",
                max_length=8,
            ),
        ),
    ]
